### ISSUE TITLE
something about the demo

### ISSUE THREAD

**Issue by vincentliu9** [mjhucla/mRNN-CR#3]
Hi,I have got a problem when trying to run the demo.I do according to the requirements and the basic installation,hopefully it is successful.Howerver,then error ocurrs when I Run cr_mRNN_demo.py.Following is the error description.

Traceback (most recent call last):
  File "cr_mRNN_demo.py", line 1, in <module>
    from concensus_reranking_utils.consensus_reranking import Consensus_Reranking
  File "/home/carl/mRNN-CR/concensus_reranking_utils/consensus_reranking.py", line 19, in <module>
    from pycocotools import COCO
ImportError: No module named pycocotools

I tried to read the program but still don't know how to solve the problem.Could you give me some suggestion please?

**Comment by mjhucla** [comment]
Please make sure that you have install the MS COCO caption toolkit. If it is installed correctly, you should find pycocotools at ./external/coco-caption.

Also the root path when you run the demo should be /home/carl/mRNN-CR

**Comment by vincentliu9** [comment]
Thanks!Maybe I got the softlink wrong as I'm not familiar with python.I changed the shell in the second step of the basic installation
"ln -sf ./external/coco-caption $PATH_COCOCap" to "ln -sf $PATH_COCOCap ./external/coco-caption"
and copy some essential files to the pycocoevalcap file such as cider_scorer_compute_sentence,eval_pair_cider
Finally it works for the demo.
